### Marga Sample HTTP Server Requests

### 1. Root endpoint - Homepage
GET http://localhost:8080/

### 2. Hello endpoint - Greeting
GET http://localhost:8080/hello

### 3. API endpoint - API information
GET http://localhost:8080/api

### 4. API endpoint with different HTTP methods
POST http://localhost:8080/api
Content-Type: application/json

{
  "message": "Test POST Request",
  "timestamp": "2024-01-01T12:00:00"
}

### 5. API endpoint with PUT method
PUT http://localhost:8080/api
Content-Type: application/json

{
  "id": 1,
  "name": "Freddy BBQ Item",
  "description": "A delicious BBQ dish"
}


### 6. API endpoint with DELETE method
DELETE http://localhost:8080/api
Accept: text/html

### 7. Test with different Accept headers
GET http://localhost:8080/api
Accept: application/json

### 8. Test with User-Agent header
GET http://localhost:8080/hello
User-Agent: FreddyBBQ-Client/1.0
Accept: text/html

### 9. Test with custom headers
GET http://localhost:8080/api
X-Custom-Header: FreddyBBQ-Test
X-Request-ID: 12345

### 10. Test root page with different Accept types
GET http://localhost:8080/

### 11. Test with query parameters (if implemented)
GET http://localhost:8080/api?name=Freddy&type=bbq

### 12. Test with fragment (if implemented)
GET http://localhost:8080/hello#section1